// Generated by gencpp from file st_pid/Pat.msg
// DO NOT EDIT!


#ifndef ST_PID_MESSAGE_PAT_H
#define ST_PID_MESSAGE_PAT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace st_pid
{
template <class ContainerAllocator>
struct Pat_
{
  typedef Pat_<ContainerAllocator> Type;

  Pat_()
    : path_()  {
    }
  Pat_(const ContainerAllocator& _alloc)
    : path_(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _path__type;
  _path__type path_;





  typedef boost::shared_ptr< ::st_pid::Pat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::st_pid::Pat_<ContainerAllocator> const> ConstPtr;

}; // struct Pat_

typedef ::st_pid::Pat_<std::allocator<void> > Pat;

typedef boost::shared_ptr< ::st_pid::Pat > PatPtr;
typedef boost::shared_ptr< ::st_pid::Pat const> PatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::st_pid::Pat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::st_pid::Pat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::st_pid::Pat_<ContainerAllocator1> & lhs, const ::st_pid::Pat_<ContainerAllocator2> & rhs)
{
  return lhs.path_ == rhs.path_;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::st_pid::Pat_<ContainerAllocator1> & lhs, const ::st_pid::Pat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace st_pid

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::st_pid::Pat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::st_pid::Pat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::st_pid::Pat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::st_pid::Pat_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::st_pid::Pat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::st_pid::Pat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::st_pid::Pat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e7e4cb758a1a3e10b6dab1976b351ef";
  }

  static const char* value(const ::st_pid::Pat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e7e4cb758a1a3e1ULL;
  static const uint64_t static_value2 = 0x0b6dab1976b351efULL;
};

template<class ContainerAllocator>
struct DataType< ::st_pid::Pat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "st_pid/Pat";
  }

  static const char* value(const ::st_pid::Pat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::st_pid::Pat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] path_\n"
;
  }

  static const char* value(const ::st_pid::Pat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::st_pid::Pat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::st_pid::Pat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::st_pid::Pat_<ContainerAllocator>& v)
  {
    s << indent << "path_[]" << std::endl;
    for (size_t i = 0; i < v.path_.size(); ++i)
    {
      s << indent << "  path_[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.path_[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ST_PID_MESSAGE_PAT_H
