// Generated by gencpp from file st_pid/Path.msg
// DO NOT EDIT!


#ifndef ST_PID_MESSAGE_PATH_H
#define ST_PID_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace st_pid
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : path_()  {
    }
  Path_(const ContainerAllocator& _alloc)
    : path_(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _path__type;
  _path__type path_;





  typedef boost::shared_ptr< ::st_pid::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::st_pid::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::st_pid::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::st_pid::Path > PathPtr;
typedef boost::shared_ptr< ::st_pid::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::st_pid::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::st_pid::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::st_pid::Path_<ContainerAllocator1> & lhs, const ::st_pid::Path_<ContainerAllocator2> & rhs)
{
  return lhs.path_ == rhs.path_;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::st_pid::Path_<ContainerAllocator1> & lhs, const ::st_pid::Path_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace st_pid

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::st_pid::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::st_pid::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::st_pid::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::st_pid::Path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::st_pid::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::st_pid::Path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::st_pid::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4482bbc958240ef8af7049ce9e00f0e";
  }

  static const char* value(const ::st_pid::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4482bbc958240efULL;
  static const uint64_t static_value2 = 0x8af7049ce9e00f0eULL;
};

template<class ContainerAllocator>
struct DataType< ::st_pid::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "st_pid/Path";
  }

  static const char* value(const ::st_pid::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::st_pid::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] path_\n"
;
  }

  static const char* value(const ::st_pid::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::st_pid::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::st_pid::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::st_pid::Path_<ContainerAllocator>& v)
  {
    s << indent << "path_[]" << std::endl;
    for (size_t i = 0; i < v.path_.size(); ++i)
    {
      s << indent << "  path_[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.path_[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ST_PID_MESSAGE_PATH_H
